coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
      frontend:
        flags:
          - frontend
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 60%
        threshold: 2%

flags:
  frontend:
    paths:
      - src/

comment:
  layout: 'reach,diff,flags,tree,footer'
  behavior: default
  require_changes: false
